### ISSUE TITLE
Alternate build script

### ISSUE THREAD

**Issue by rrag** [esbullington/react-d3#109]
I had to use windows for a few days and the `npm run build` and `watch` do not work on the windows version since `mkdir -p` does not exist on windows cmd and the `mkdir` command returns an error when the directory already exists aborting the `npm run ...`. It spent too much time than I cared to on that problem and had to give up after some time.

I can create a gulpfile.js for the current build and send it over are you cool with that? or do you have other plans?

**Comment by esbullington** [comment]
Hey @rrag I'm sorry you had to spend so much time on it.  jmuel and I made some improvements to the build script today but I didn't realize the `-p` flag on `mkdir` didn't work on Windows.  I was definitely aiming for cross-platform commands.

Ideally, I'd like to just use a `Makefile` but I know that there are cross-platform issues there, too. And if I'm accepting contributions from devs working on Windows machines, then they deserve to have a build tool that is easy for them to work with.

So yes, if you think Gulp is the best cross-platform answer to our problem, then I'll gratefully accept a PR for a gulpfile.js.  But let's please leave the current npm scripts in place until we're confident that the gulpfile has matched all of those scripts' current capabilities.

**Comment by jmuel** [comment]
I actually prefer Gulp as well. Just using NPM scripts is nice when things are simple but even in this project so far we've had issues with globally installed react-tools and not maintaining aliases, both of which are hard problems to have with Gulp. I'd really appreciate this.

**Comment by rrag** [comment]
why do we need this

`jsx --harmony -x jsx src build/cjs && jsx --harmony src build/cjs`

portion of the `release`?

Can I skip that step and just generate `react-d3.js` and `react-d3.min.js`

**Comment by esbullington** [comment]
@rrag We need that portion of release because I need to compile the JSX files into pure JS files in their own package directory, which I then use to publish.  The directory is `build/cjs`.  The resulting build in that `build/cjs` directory is the definitive build that I publish to NPM. The react-d3.min.js is just for the JSFiddle, it's got React and d3 both packaged in (haven't been able to get a browserify standalone build to accept a global reference to dependencies, even though there should be a way).  Both the documentation charts that we publish to the website and the minified build for JSFiddle are just there for documentation and examples.

**Comment by esbullington** [comment]
We don't want to publish the NPM package from anything like an aggregated react-d3.min.js that's not since we want people to be able to `require` the charts separately.  Plus that react-d3.min.js build is a standalone build not meant to be published to npm.

And the reason I have to run the jsx twice is because the command doesn't accept multiple file extensions, and I like differentiating pure JSX from js files via extension (and we use jsx to not only transform jsx but also to transpile es6).

If you'll look at the result of the build to the `build/cjs` directory, you'll see what I need to build to publish to NPM.  Pure JS, with all JSX transformed to JS, and all ES6 transpiled to JS.

**Comment by rrag** [comment]
got it.

I can add a step to create the `.js` files from `.jsx` using some plugin, need to spend some time to figure out the right plugin.

> it's got React and d3 both packaged in (haven't been able to get a browserify standalone build to accept a global reference to dependencies, even though there should be a way)

Good to know, I know the options to fix that, I can modify the gulpfile to take `react` and `d3` as `external` and then have a `browserify-shim` configuration in `package.json` where I say 

`react: "global:React"`,
`d3: "global:d3"`

The `watch` task now takes almost 1.5 secs to build on change of any file because of this, if I exclude it the build is much faster.

**Comment by esbullington** [comment]
I'm closing this one since the Gulp build system was merged.  Well done, rrag!

**Comment by rrag** [comment]
Sure. I was thinking about adding a `gulp publish` task also.

https://gist.github.com/bevacqua/8492639

but I am not too thrilled with it since it is spawing a child process

**Comment by esbullington** [comment]
Thanks but I'd prefer to do the publish manually, since I like to go and check the compiled code before I hit publish (paranoia after I accidentally published jsx code once, and es6 code another time, both times quickly corrected).

I may add npm scripts that point to the appropriate gulp commands, since that's what my fingers are used to doing.  But I'll take care of that.  

Browsersync is cool, I've only used LiveReload before this.

Is the Gulp system working well on Windows?
