### ISSUE TITLE
Example data for line chart is out of date

### ISSUE THREAD

**Issue by jakepusateri** [esbullington/react-d3#116]
http://esbullington.github.io/react-d3/ has example data for the line chart, but this data causes an error. Uncaught TypeError: Cannot read property 'forEach' of undefined. This appears to be because the data input format has changed.

**Comment by esbullington** [comment]
Thanks @jakepusateri That's a link to the old documentation site -- I need to just take it down.  It's updated with the [new site](http://esbullington.github.io/react-d3-website/) at the top of the Github site, but the NPM site still has it up because I've not yet published a new release since I updated the website in the package.json (this has all been the past 3-4 days).

Anyway, I'll leave this up until I have the old site closed down and a patch NPM version released to update the website on the NPM site.

**Comment by esbullington** [comment]
OK, I think I have everything updated now, and the old `gh-pages` branch on this repo is deleted.  Thanks for the issue!   Please feel free to open another if you find anything.
