### ISSUE TITLE
allow for individual component requires

### ISSUE THREAD

**Issue by srcspider** [esbullington/react-d3#120]
Currently this is the recommended way of including react-d3,
```js
var rd3 = require('react-d3');
var BarChart = rd3.BarChart;
var LineChart = rd3.LineChart;
var PieChart = rd3.PieChart;
var AreaChart = rd3.AreaChart;
var Treemap = rd3.Treemap;
var ScatterChart = rd3.ScatterChart;
```
While convenient it adds a lot of unnecessary bloat. Even if I'm maybe using all of them on the site I may only be using one or two per page, so loading all of them into every page is unnecessary bloat.

Another issue with this approach is that it doesn't scale up well. The more charts/etc are added the bigger it grows. Not very good for updates when the library just gets bigger with no code change.

Alternative approach,
```js
var LineChart = require('react-d3/LineChart');
var BarChart = require('react-d3/BarChart');
```

**Comment by esbullington** [comment]
This is a good point.  Your alternative approach is actually possible now, by doing this:

    var BarChart = require('read-d3/barchart').BarChart;

The reason you can't just do:

    var BarChart = require('react-d3/BarChart');

is because the barchart module contains several constituent components, all of which I export so advanced users can't make their own charts as they wish (this is why I don't capitalize it, because it's more than just a single exported component).

However, I'm looking toward moving to a different project structure in the next few releases, where the chart primitives will be in their own library.  Which will allow us to possibly adopt the exact syntax you propose.

But the bottom line is that you can just require a single chart now.  I just updated the README accordingly.
