### ISSUE TITLE
Is the pub-sub system necessary?

### ISSUE THREAD

**Issue by frederickfogerty** [esbullington/react-d3#127]
I think not.

[From the React Docs](http://facebook.github.io/react/tips/communicate-between-components.html): 
> For parent-child communication, simply pass props.

The current pub-sub system is included for what I can only assume is convenience. The reason I am requesting to remove it is that I am trying to stop the Voronoi events from triggering when the user is brushing (I have Voronois and brushes working together), and having a pub-sub system means that a parent component has little control over its child components. Since the graphs have a strict ancestor-child relationship, I think passing a callback through props is a much better solution (and is what I've implemented in my code).

**Comment by esbullington** [comment]
Are you passing props and using Flux?  You had mentioned Flux before.  And unless you've made significant changes to the structure, the Voronoi overlay is a sibling component to the data series it interacts with, not parent-child.

Passing around callbacks rapidly up and down the component tree becomes a pain in larger React apps -- I've tried it.  Just like plain pubsub, it's OK for a few communication channels, and then it just because a headache.

This is all stuff I had planned on tacking in the time leading up to 0.5, as part of implementing data frame animations.  However, I may need to tackle this sooner, in order to do tooltips and plus your issue here.  In particular, I was looking at using cursors for application state, like Om does, but I need to do some testing to see how they handle rapid fire-and-forget events.  We may need to move to Flux, which is just a unidirectional variation on our current pubsub system.  I'm just not sure how appropriate Flux is for a React library.

I'm still thinking about this one.  Input is welcome.

**Comment by esbullington** [comment]
By the way, to be clear, the pubsub system was never meant as a permanent solution, just a quick way to get up a Voronoi overlay.  We may be at the point with brushes as well as tooltips where we need to move to a permanent solution, even before 0.5 animations like I had planned.

**Comment by frederickfogerty** [comment]
I'm gonna go ahead and PR my code when it's finished then

**Comment by rrag** [comment]
@frederickfogerty are you working on this now? I just started to swap out `immstruct` with `freezer-js` on the `LineChart`, making sure we are not working on the same thing.

**Comment by frederickfogerty** [comment]
@rrag Nope, I've recently changed jobs, so won't be working with graphs as heavily any more.

**Comment by yang-wei** [comment]
Since pubsub system is not used anymore, I'll just close this.
