### ISSUE TITLE
So many renders

### ISSUE THREAD

**Issue by jefffriesen** [esbullington/react-d3#143]
I was building a custom component based off line chart and noticed that the primary render function renders ~50 times when the page is refreshed. I thought I had set something up incorrectly but then I checked on the unadulterated LineChart and BarChart - both do it too. I didn't see any obvious reasons for it though. Anyone else get that?

**Comment by yang-wei** [comment]
Would be helpful if you can show us with fiddle perhaps ?

**Comment by esbullington** [comment]
Yes, if you could provide an example of this happening, it would be helpful.  But no, there should be nothing inherent to the chart components themselves that would cause the top-level component to re-render ~50 times.

You may know all this, but if not, a brief note to bear in mind about React: if any parent components of the chart component set state for any reason, like would result from an async request in `componentDidMount`, each time that happens the chart component will re-render unless you tell it not to in `shouldComponentUpdate` (and only do that if the chart data really didn't change, if it did you need it to re-render).

So in the example charts here, the charts render 3 times, because their parent component has two async requests that set state in the top component's `componentDidMount`, plus the initial render.

Normally, I would say don't worry too much about all this unless you're seeing performance issues, but it's probably a bit excessive to be rendering the chart component 50 times.  So unless you're actually updating the data that many times, I'd look at inserting a check in the parent component's `shouldComponentUpdate` to check if the data has updated, and otherwise return false.  This should cut down on those updates.

I'll actually be going through soon and doing these types of optimizations myself for react-d3 using the `shouldComponentUpdate` method or React's `pureRenderMixin` mixin.  But I've not yet seen any performance issues that would call for that, I'll just be prematurely optimizing at that point (actually, it's in anticipation of upcoming frame animations, so I'd like to think it's not really premature).

However, if something else is happening in your case, or you think it's a bug, a JSFiddle or some other example of what's happening would be really helpful.

**Comment by jefffriesen** [comment]
If this isn't happening on your end then apparently it's on mine. I can recreate it with a trivial setup where I'm sure I'm not calling render excessively, however, I'm using Morearty at the moment so that may have something to do with it. I'm going to close this, assuming it's on my end. If I find something otherwise I'll reopen it. Thanks
