### ISSUE TITLE
LineChart xTicksCount does not work

### ISSUE THREAD

**Issue by rzeszutekjacek** [esbullington/react-d3#144]
hello :)

according to: https://github.com/esbullington/react-d3/blob/master/src/linechart.jsx#L424
I see that it should be possible to set number of ticks on x axis of LineChart.

However, the code:
```
<LineChart
                  legend={true}
                  data={chartData}
                  width={800}
                  height={500}
                  xAxisTickCount={4}
              />
```
still have random number of ticks (higher than 4).

Any plans to fix/add this feature ? :)

**Comment by esbullington** [comment]
Behind the scenes, `xAxisTickCount` is using d3's `axis.ticks()` method, which uses [says the following](https://github.com/mbostock/d3/wiki/Quantitative-Scales#linear_ticks) about the count provided: 

"The specified count is only a hint; the scale may return more or fewer values depending on the input domain."

To get the kind of control you're wanting, we need to pass in an array of values to d3's `tickValues`, which let's you provide the tick values expressly.  I'll probably expose that functionality when I merge all the axis props into a single axis object for v0.4, I'll have to think about it.

Otherwise, you can provide the `tickValues` yourself by passing through a `tickValues` prop to your charts `XAxis` (or `YAxis`) component and then down into the `AxisTicks` grandchild component.

**Comment by esbullington** [comment]
I'm going to go ahead and close this issue due to lack of activity, and because it appears to be an artifact of the way d3 handles the ticks.  Feel free to open another issue if you think it's something we can solve.
