### ISSUE TITLE
Line graph voronoi error

### ISSUE THREAD

**Issue by boucher** [esbullington/react-d3#149]
I'm running into a problem creating a simple line graph that seems to fail when trying to construct the mouseover voronoi. Here's (roughly) the graph I'm constructing:

    var lineData = [{"name":"Series 1","values":[{"x":0,"y":0},{"x":1,"y":1},{"x":2,"y":2},{"x":3,"y":3},{"x":4,"y":4},{"x":5,"y":5}]}];
    return <LineGraph  data={ lineData } width={ 500 } height = { 300  } />

And the trace (with much React clutter clipped)

    Uncaught TypeError: Cannot read property 'x' of nulld3.js:5232 
    d3_geom_voronoiHalfEdged3.js:5044 
    d3_geom_voronoiCloseCellsd3.js:5459 
    d3_geom_voronoid3.js:5475 
    voronoivoronoi.js:46 
    exports.Voronoi.React.createClass.renderReactCompositeComponent.js:1260 (anonymous function)

specifically, in the debugger, rSite is null in this expression:

    this.angle = rSite ? Math.atan2(rSite.y - lSite.y, rSite.x - lSite.x) : edge.l === lSite ? Math.atan2(vb.x - va.x, va.y - vb.y) : Math.atan2(va.x - vb.x, vb.y - va.y);

Any ideas? At the moment, just the ability to suppress the mouseover would be desirable but obviously so would fixing the underlying issue.

**Comment by esbullington** [comment]
If I had to guess, then I'd say one of your nested objects in your `values` array is empty, or just contains the `y` property or some other property and not the `x`.

Now, it's a reasonable question as to whether this type of error should be handled more gracefully by the library (see #96), but if you're looking for a quick answer, I'd recommend trying to filter your data for missing `x` values and see if that works.

**Comment by boucher** [comment]
Yeah, unfortunately that isn't the case. The data array making it all the way down the chain is visible in the debugger as being 0,0, 1,1, 2,2 3,3 4,4 5,5.

**Comment by esbullington** [comment]
Oh, so that's the actual data?  In that case, I just tried that data and it's working ok here.

Are you on `master` or the latest NPM version?

**Comment by boucher** [comment]
Latest npm, which reports to be 0.2.1, but master and all the branches I see claim to have a version of 0.2.0, which confused me.

**Comment by esbullington** [comment]
Yeah, I'm rolling in the process of testing and rolling out a new release and accidentally wrote 0.2.0 instead of 0.3.0 (still working on things).

I have no idea why you're getting that error on 2.1.  I've just checked out that release and am running your data just fine.  Here's a [working JSFiddle](http://jsfiddle.net/esbullington/n67d8p77/) of your chart with that exact data, using the latest release, although I also have it working on a checked out v0.2.1 (and if you look back far enough, you can probably find the JSFiddle that accompanied 2.1 to confirm).

I'll be publishing 0.3.0 in the next day or so, so feel free to try again with the new version if you think it's v0.2.1 that causing the trouble.

**Comment by boucher** [comment]
Thanks, I'll try and see if I can create a reduction tomorrow, and I'll try the latest in the 0.3 branch as well.

**Comment by boucher** [comment]
Ok, so, the specific difference in my case that causes it to reproduce is the value for width. If you provide a width of 672 and a height of 300 it should fail. Full react class I ran to produce the failure:

https://gist.github.com/boucher/2213644b2b627ed4aa36

**Comment by boucher** [comment]
I also had some difficulty getting the current master to build. Seemingly some issues with transpiling es6 (many similar errors):

    [23:38:49] [Error: Parsing file chart-boilerplate/node_modules/react-d3/src/linechart/LineChart.jsx: Unexpected token (73:10)]

**Comment by esbullington** [comment]
What command are you running to build?   If you're wanting to build a full build you can use in an environment that doesn't support JSX and ES6, you need to run `gulp release` and then use the package generated in the build/cjs directory.

BTW, I just figured out what's causing your issue.  It's an undocumented (but previously discussed) quirk of d3's voronoi function (which we use) that doesn't like collinear points, or graphing the identity function like you're doing here.  In terms of how to solve  it, I'm thinking of a good approach, but in the meantime, you'll need to add a tiny bit of jitter to any one of your points, such that the x values no longer equals the y value.  I'm also going to add restore a previous config option to disable the voronoi-based animation, which is probably the best thing to do if you're graphing colinear series or the identity function.

**Comment by boucher** [comment]
I had forgotten that the build step was my own test bootstrap and not the react-d3 build, sorry about that. I came across those colinear discussions and assumed that was the issue, but wasn't really sure exactly how it was triggered. I'll probably adopt the randomness approach for now, but I agree that having an option to turn off the mouseovers would be nice. Thanks for your help.

**Comment by esbullington** [comment]
I did add a `hoverAnimation` prop in the line chart to disable animation in cases when you want to turn off the mouseovers, and it's already in the scatter chart implementation.  So given that this is probably the best workaround at this point, I'm going to go ahead and close this issue.

If you have any ideas on how to approach the core issue with colinear points, you'd probably want to file that issue with d3, since that's where our voronoi function comes from.

But if you have any other problems with react-d3, please feel free to file another issue.

**Comment by boucher** [comment]
Cool, thanks. I did end up just adding a bit of random noise in the
meantime.
