### ISSUE TITLE
Are npm dependencies correct?

### ISSUE THREAD

**Issue by jefffriesen** [esbullington/react-d3#16]
I am having problems using this library within a repo. With a forked repo installed locally, I used npm link so that I can edit it while using it in another repo. I've done this before with other libraries and apps without a problem with the dependencies in this library. The react-d3 works fine if I install the remote repo, but it's hard to work that way.

The error I'm getting is this: `Cannot read property 'firstChild' of undefined` which is commonly reported as a conflict between to React libraries. (http://stackoverflow.com/questions/27153166/typeerror-when-using-react-cannot-read-property-firstchild-of-undefined)

I'm wondering if React should be a dependency. Looking at these popular repos they have React in peerDependencies: 
https://github.com/react-bootstrap/react-bootstrap/blob/master/package.json
https://github.com/rackt/react-router/blob/master/package.json

I don't know much about peerDependencies though. Any insight would be great. 

Also, should jsdom be a dependency? I know that d3 depends on it, but webpack or browserify should pull it in through d3.

**Comment by esbullington** [comment]
Having looked into this, I don't yet have an answer for why `npm link` isn't working.  But I can answer a few questions:

1. I was not previously familiar with peerDependency, but I'm pretty sure React should not be a peerDependency of React-d3.  It's seems to be for plugin-host type relationships, whereas we depend directly on React to render to the DOM.  In any case, I'm pretty sure that shouldn't make any difference for your issue.

2. Yes, you're correct that jsdom should not be a dependency.  Originally, I had it listed as a dev dependency since I was using it directly for testing, but don't remember how it ended up in dependencies.  I've taken it out and it's now pulled in through d3.js and working fine for me.

Also, I had another error in package.json, which was that React was listed under both dev dependencies and dependencies.  I've now corrected this, but because of this error, you may have somehow pulled in different versions of React which is causing this problem?  Maybe pull in the new commits, delete the installed node package, try cleaning (`npm cache clean`) and reinstalling now?

**Comment by esbullington** [comment]
@jefffriesen  OK, I hope I've fixed your issue here.

 Could you try to pull in my latest changes on master, run `npm run build`, change to the directory `build/cjs`, and then run `npm link` like you normally do?

If that works OK, I'm going to go ahead and publish release 0.1.0 on npm.

Thanks for your help!

**Comment by jefffriesen** [comment]
I'm having some different problems now but I don't think it's related to this. Thanks for checking into and updating the dependencies. I'm going to close this.
