### ISSUE TITLE
Y axis rendering cuts off more than 2.5 digits.

### ISSUE THREAD

**Issue by jmuel** [esbullington/react-d3#160]
http://jsfiddle.net/p4kb3ptv/

That fiddle should demonstrate the problem. If the y-axis has more than 2 digits it cuts the third digit off and doesn't render 4+.

**Comment by esbullington** [comment]
Hey, thanks for the bug.  This is something that's very hard to adjust for automatically, since you have to render the entire chart on the actual DOM (not virtual DOM) before you can detect how long a text string will render.  Since we use the virtual DOM only (so people can do server-side rendering), this isn't possible for us to do at this point, and probably ever.  So we have to chose some arbitrary margin width, which can sometimes cut off longer numbers.

Fortunately, the solution is simple enough: pass in custom margin props to your chart component.

`margins={{top: 20, right: 30, bottom: 30, left: 40}}`

As you can see, this turns out fine:

http://jsfiddle.net/esbullington/hhu87pkg/

**Comment by esbullington** [comment]
I'm closing this issue since it should be solvable with the `margins` property.  If you have any trouble with that, please feel free to open a separate issue.

**Comment by jmuel** [comment]
I took a look at this and it seems like enough to fix the issue. I was really hoping for a better solution but you're right, this is the best answer I can see. I might take a look at updating the docs to make a note of this since it's something I can see other people having a problem with.
