### ISSUE TITLE
AxisTicks component appears to ignore tickFormatting prop

### ISSUE THREAD

**Issue by jakepusateri** [esbullington/react-d3#162]
https://github.com/esbullington/react-d3/blob/master/src/common/axes/AxisTicks.jsx#L38 is checking for a tickFormat_ prop for some reason and there's an extra tickFormat defaultProp. 

Meanwhile props.tickFormatting isn't used at all.

**Comment by esbullington** [comment]
Thanks for letting me know.  I swamped right now with client work since I was out sick for over a week this month, so it will probably be at least the weekend before I can get to this.

Most of the code in the `AxisTicks` component is directly pulled from d3, so that's the reason for extraneous variables.  It definitely needs cleaning up.

**Comment by yang-wei** [comment]
fixed by #165
