### ISSUE TITLE
displayName = "exports" for all components

### ISSUE THREAD

**Issue by rrag** [esbullington/react-d3#163]
Since all the components are created as 

```
module.exports = React.createClass({
```

The display name is `exports` for everything. You can see it in the Chrome React dev tools

![image](https://cloud.githubusercontent.com/assets/10691183/6760212/abb461f6-cf14-11e4-9a43-899ab8b4b3dc.png)

Fix:

create
```
var LineChart = React.createClass({
...
})

module.exports = LineChart
```

**Comment by parshap** [comment]
You can also pass `displayName` as a property to `React.createClass`.

```
module.exports = React.createClass({
  displayName: "LineChart",
  // ...
});
```

**Comment by esbullington** [comment]
Thanks for the issue. I don't use React Dev tools much, so I wasn't aware of this issue until now.

Just to be clear to anyone reading, this is only an issue affecting React Dev tools: it doesn't have any impact on the actual HTML generated.

This issue is also the result of a totally standard CommonJS idiom, so I'm not the only one to have problems with this: I see that react-bootstrap and react-router have also run into this issue recently [here](https://github.com/rackt/react-router/issues/577) and [here](https://github.com/react-bootstrap/react-bootstrap/issues/1).  To be fair, there's not much React Dev tools could do to avoid it.

I'll go through and fix this, probably using `displayName`, but as I wrote in another issue filed today, I'm also scrambling to catch up with my paid work after being out of work well over a week, and I'm also interviewing in the coming weeks, so it'll probably be a while before I get to it.

**Comment by boucher** [comment]
Yeah just got bit by this, I was actually using displayName to figure out what kind of chart I was dealing with programmatically (perhaps that was lazy, I'm changing it).

**Comment by yang-wei** [comment]
Send us a pr after you're done =) @boucher
