### ISSUE TITLE
Unable to show x/yAxis Label

### ISSUE THREAD

**Issue by delaneyj** [esbullington/react-d3#177]
Looking at the code it appears your are using props.xAxisLabel/props.yAxisLabel  but when i try in a [JSFiddle](http://jsfiddle.net/56hjgdsf/3/) they don't show up.  Any thoughts?

**Comment by esbullington** [comment]
Hey, that functionality was just added to bar chart a few days ago, and I haven't yet updated the build in the JSFiddle.  So that will require using `master` until I publish a new NPM version and update the JSFiddle (I'll try to do that in the next few days).

Axis labels should work just fine with all the other charts that have X and Y axes -- the bar chart is the only one that recently picked up that feature.

**Comment by delaneyj** [comment]
Awesome!  I'll make to be on the lookout for > 0.3.0 version.  Would be great to keep this open until its in the released version.

**Comment by esbullington** [comment]
> Would be great to keep this open until its in the released version.

Agreed.

**Comment by esbullington** [comment]
@rrag can you give me a hand whenever you get a spare moment?  To solve this issue, I've been trying to get your Gulpfile `minified` task to build a new minified package to use in the JSFiddle, but each time I try, I get an error on JSFiddle telling me there's no `rd3` variable.

It looks like you're using the `standalone` flag in browserify, so I'm not sure why it's not exposing the rd3 namespace.

I'm using the latest version: v0.3.1.  Any ideas?  Can you get it to build a version that will work on JSFiddle?  If possible, I'd prefer to use your Gulpfile `minified` task rather than my `npm` task since you don't pull in another copy of React like mine does.

Thanks!

**Comment by rrag** [comment]
@esbullington  did you try [this](http://jsfiddle.net/rrag/8617n0qk/)? I had added the comment to this [PR](https://github.com/esbullington/react-d3/pull/154#issuecomment-83146260)

**Comment by esbullington** [comment]
@rrag thanks, I saw that, and it worked fine if I recall.  That was generated by gulp, right?  For some reason, I can't get it to work now.

**Comment by yang-wei** [comment]
Close due to inactive. Please open a new issue to make further discussion.

**Comment by yang-wei** [comment]
gi
