### ISSUE TITLE
Unable to turn off % at the end of a value in a PieChart.

### ISSUE THREAD

**Issue by delaneyj** [esbullington/react-d3#178]
Always displays a percentage even when not desired.  Are there props that could be exposed to turn off or switch the suffix?

**Comment by esbullington** [comment]
Thanks for bringing this up.  When I hard-coded this in, I was thinking of the fact that it's rarely (never?) a good idea to make a pie chart whose parts don't add up to a whole.   But obviously, there are more ways to represent parts of a whole other than percentages, so users should have the option to exclude it.

Before the next version, I'll change the pie chart to accommodate the same type of formatting functions you can use in the other charts, although I may still keep a percentage suffix as the default formatter.  A formatting function would even allow you to do something like put percentages in parentheses.

I'll reference this issue when I make the commit, although it will probably be at least several days.

**Comment by yang-wei** [comment]
I don't mind to tackle this issue but I am not quite understand with the phrase 
 > change the pie chart to accommodate the same type of formatting functions you can use in the other charts

Mind to explain? @esbullington

**Comment by esbullington** [comment]
> Mind to explain? @esbullington

@yang-wei sure, glad to.  In all the charts based on Cartesian coordinate system, we can pass in an `yAxisFormatter` function or `xAxisFormatter` function.  This function takes whatever value is at the tick position in question as the function input argument, and then it returns the formatted value.  

So in this case, since there's obviously no x/y axis or ticks, we could just use a `formatter` property that takes a function.  In the case of a percentage sign, the function would look like this (in es6):

`(val) => val + '%'` 

If we wanted to format that with as a currency or something, we'd do:

`(val) => val + '$'`

Does this make sense?  Using a function instead of just a suffix or prefix string lets us be much more flexible.

**Comment by yang-wei** [comment]
@esbullington Yes this makes sense of course. Thanks! 

Since piechart is not a Cartesian chart, so I expect another mixin to be created?

**Comment by yang-wei** [comment]
@delaneyj Will be fixed in #190 once it's merged. Thanks
