### ISSUE TITLE
Ability to scale using width/height using percentages.

### ISSUE THREAD

**Issue by delaneyj** [esbullington/react-d3#179]
Would it be possible to the svg calls inside a viewbox to make the charts more responsive to layouts than a fixed size?

**Comment by esbullington** [comment]
Yes, you can set a viewbox now.  Just pass a `viewbox` property to any chart with the appropriate viewbox settings. I unfortunately haven't documented this yet -- it's relatively new.

Or do you have something else in mind?

**Comment by esbullington** [comment]
I'm closing this one, but if setting the `viewbox` didn't work for you, please feel free to file another issue.

**Comment by samdalton** [comment]
@esbullington  I'm also running in to this issue. If I have a chart I want at 600x300, and I set my `viewBox` to "0 0 600 300", I still need to set `width` and `height` props on the chart (AreaChart, in this case) because they are used to compute the axis scale - https://github.com/esbullington/react-d3/blob/master/src/areachart/AreaChart.jsx#L46. For this reason, I can't pass in width:100%, height:100% to have it scale to it's parent container.

I was thinking of 4 props, `viewBoxX`, `viewBoxY`, `viewBoxWidth`, `viewBoxHeight` which the width and height respectively could be used to compute axes' scales etc., and the top-level `width` and `height` props are solely passed in to the svg chart as width/height attributes. This way, any internal measurements will be consistent with the viewBox, and the outside dimensions can be set to whatever.
