### ISSUE TITLE
BarChart needs renderAxis

### ISSUE THREAD

**Issue by unbracketed** [esbullington/react-d3#19]
The axes don't display on the initial render of BarChart. It looks like this has been solved in other components (line chart) with use of `_renderAxis` for `componentDidMount` and `componentWillReceiveProps`

**Comment by esbullington** [comment]
Is this server-side rending?  Yeah, it's been addressed in other charts.  The reason we have to run it in componentWillReceiveProps is the axes use d3 to generate svg, so that occurs outside of the React's virtual DOM accounting.  As a result, when React is updated with new props, it re-renders to chart and so we need to re-render the axes manually.  Ideally, we'd move toward a pure React axes, but I've looked into the amount of work that will require and haven't had time for it yet.

**Comment by unbracketed** [comment]
This is client-side. Thank you for the explanation and I understand the reason for running the logic in componentWillReceiveProps. Regardless where the component is rendered, `cWRP` doesn't get called during the initial render so all components will need to the same logic run in `cDM`.

**Comment by esbullington** [comment]
Thanks again for the PR (merged).  Just wanted to let you know I'm currently doing the same on the area chart, so we don't overlap efforts.  I'm also looking into chart axis mixins, so perhaps we can remove the code repetition altogether.

**Comment by unbracketed** [comment]
:+1:

**Comment by esbullington** [comment]
Fixed areachart with same approach in #21.
