### ISSUE TITLE
Better approach to handle animation in chart with voronoi(scatter chart etc)

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#201]
Currently our `voronoi` and `dataSeries` are in sibling relationship. When a `polygon`(child) in a `voronoi` emit a event(`mouseOver` or `mouseLeave`), it needs to go to the top of `voronoi` and again propagate down `circle` which is child of `dataSeries`. To manage this kind of hierarchy, we used library like `cortex` or  `immstruct`. Somemore we have to consider the circle `id` to make sure correspond element is animated.

```
           graph  ------------------- --------- ...
           /        |                 \
          /         |                  \ 
         /          |                   \
   voronoi     dataSeries            dataSeries           ...
       |             |                   |
       |             |                   |
   polygon        circle            circle            ....
   (child)         (child)         (child)
```

Apparently, we don't like this approach. Writing test in this case is difficult, our test becoming like this
```javascript
...
expect(circleOne.props.r).to.equal(pointRadius);
// seems unnatural
structure.cursor('voronoi').cursor(circleOne.props.id).update(()=> 'active' );
expect(circleOne.props.r).to.be.above(pointRadius);
expect(circleOne.props.fill).to.not.equal(circleOneColor);
...
```

I decided to go simple way, the `parent-child` relationship. I would like to avoid the `sibling` relationship. So here is the approach I suggest.
```
     graph
         |
 dataseries (=== voronoi) ------------- ------- ...
        |                              |
CircleAndPolygonContainer           CircleAndPolygonContainer     ...
    /        \                              /              \
Circle   Polygon                         Circle         Polygon 
```

This way we wrap `Circle` and `Polygon`(voronoi segment) into a Container which handles all the state. Re-render also happens only Container level and we don't have to think the `id` of elements.

But...
-----

Of course, there are downsides for this approach. What I can think of is
 * By flattening all data into `allValues`, we no longer know which points belong to which series and we are unable to manage the data of each series. For example, if we want to highlight all the data for each series(in a line chart). But regarding line chart, I don't think we have to implement voronoi on it. However this will be another issue.

**Comment by esbullington** [comment]
Hey, I definitely agree that the current Voronoi approach is suboptimal.  It would be nice to keep all the needed state within a little component, and then use immstruct from an external wrapper whenever we add animations.  And I like your general approach here a lot.

A few issues:

* There's no way now to toggle animation on and off (this would be easy to fix)
* This breaks my goal of keeping React state in top-level components (this isn't necessarily a dealbreaker, but it's a compromise)
* Why not combine the `Polygon` and `CircleAndPolygon` components into one component, named `Circle`?  The polygon is needed for the animation, but it's also incidental to the component's primary purpose, which is to display a circle.
* The main issue is what to do with the line chart -- I'm not sure how much we'll benefit from dropping the Voronoi from the scatter chart when we still have to keep the same Voronoi approach along with the immstruct dependency for the line chart.

Let me think about this a little bit, mostly what to do about the line chart.  One possible approach is just to abandon the Voronoi entirely for the line chart, and instead superimpose a wider line over each chart line to capture the mouseover event.  That won't work quite as well as the current approach, since use interactions at the top of a chart wouldn't trigger any animations, but it would allow us to drop the `immstruct` dependency.

Can you think of any other approaches for capturing mouseovers for the line chart?

**Comment by yang-wei** [comment]
@esbullington Thanks for the issues.

> This breaks my goal of keeping React state in top-level components

By top-level components, do you mean the `dataSeries` and `voronoi` level? To make sure not all `circle` are re-rendered when state change, I am keeping state at the lowest possible level. Here, I am classifying components into [smart and dumb](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) where smart component(In this case, `CircleAndPolygon`) handles state. 

> Why not combine the Polygon and CircleAndPolygon components into one component, named Circle?

Agreed. Polygon seems unnecessary here.

>  it would allow us to drop the immstruct dependency.

`immstrcut` is only used for a few charts here, this will be great benefit.

> Can you think of any other approaches for capturing mouseovers for the line chart?

Yes, I can't promise you anything yet but I got something on this. Will push another commit and let you know when I come out with the idea.

**Comment by MatthewHerbst** [comment]
@esbullington and @yang-wei : What about implementing Flux or Reflux (my preference of the two) architecture to handle the animation states?

**Comment by yang-wei** [comment]
Although I never really use Flux but @esbullington had mentioned this before. This is one of our consideration too. But for now we are trying to make it small and independent on external library (only d3 and react).

**Comment by MatthewHerbst** [comment]
I think [this is a good post to read](http://blog.ryanflorence.com/you-cant-not-have-a-framework.html) as a comment about that. It's a bit more expansive than what we are talking about, but I think the basic point applies: if we don't use an external library for something as big as state management (and it can get quite big, especially in the future as `react-d3` grows), we will simply be making our own, and we probably won't do it as well. The `Store` components of `Flux`/`Reflux` are very light. Also, the more we write now, the harder it will be to switch to another library in the future if we want to.

**Comment by yang-wei** [comment]
Have to agree with you @MatthewHerbst . If flux can solve our problems here, then we'll probably remove immstruct =)

What do you think @esbullington

**Comment by esbullington** [comment]
Ideally, each chart would be stateless and deterministic.  We break that rule of thumb only for the mouseover interactions, which take place after a chart is fully rendered.

Flux is fine for applications (I've built a large application that used Flux).  Ideally, I'd like to stay away from Flux for what should be simple library components.  That said, the Voronoi mouseovers have been tricky, because they are presently non-local and require us to carry some React state, and to communicate that state among components (including among sibling components in current implementation).  But yang-wei's new implementation avoids sibling components.  

Cursors are an excellent immutable alternative to Flux for React state, which is what we're using in `immstruct`.  Cursors can almost everything that Flux can, with much less complexity, which makes them ideal for small applications and libraries.  Here's [a discussion](http://www.reddit.com/r/reactjs/comments/2v5crm/flux_vs_cursors/) re: using cursors in React on Reddit including the developer of `react-cursor`.  Cursors also make some great optimizations very easy to do (that sadly I haven't yet done).

The only problem is that `immstruct` depends on `immutable.js`, which is a great collection of immutable structures but rather large -- frankly too large for us as a library project.  I only stuck in `immstruct` because I was familiar with it and was having trouble getting `freezer`, the alternative cursor implementation we had decided on, working properly (I'm sure it was my fault).  `react-cursor` would be another excellent, smaller alternative to `immstruct`.  The other alternative is to drop the need for sibling communication and immstruct altogether, which is what yang-wei's approach here does.

So I'd gladly accept a PR for `freezer` or `react-cursor`. But I'm hopeful we may be able to drop `immstruct` even without switching to a smaller cursor implementation.  But I'm not too keen on using something as complex as Flux for a library component that only needs external state for 1 single feature.  I'm interested in reducing complexity as much as possible, and Flux adds a lot of unneeded indirection and complexity (which is fine for some applications, but not us).

I've become increasingly convinced that the only other feature for which we would need external state, which is the proposed frame animation feature, should store their state in a parent wrapper component and simply pass the new data in when needed, and then the React component would react to the update by transitioning to the a new position.  I've been holding off on doing this until React decides upon a more flexible replacement to `TransitionGroup` for React animations (I know chenglou at Facebook has been [working on this](https://github.com/chenglou/react-tween-state/issues/15) but I'm not sure what the status is).

@yang-wei the more I've thought about your approach here, the more I like it.  Why not combine your current `Polygon` and `CircleAndPolygon` components into one component, and call it `VoronoiCircle`?  I agree that it's generally good practice to break down components as much as possible into smaller components, but in this case, I like the idea of a self-contained Voronoi-capable circle (which happens you feed polygons to capture the mouse events).  Also, can you think of an easy way to switch off the animations, so users can turn off animations?  If you get around to making these changes, I'd definitely be in favor of merging it, and then seeing what we can do to eliminate the `immstruct` dependency in the line chart.
