### ISSUE TITLE
Better way to scale

### ISSUE THREAD

**Issue by jmuel** [esbullington/react-d3#204]
I was running into an issue getting the scaling to work easily so I made a few small changes shown [here](https://github.com/jmuel/react-d3/commit/9a25085510f390757c759609068ffcbfaee0f057). This isn't a complete solution so I'd have to go through the use cases that would be affected by this, but it works for my use case and can be generalized.

**Comment by esbullington** [comment]
It's a good approach if your parent element scales (like if you're using Bootstrap or some other grid-based CSS system).

You know what, we could just make width and height strings and then users could either put the pixel width/height or `100%`.  That would allow users who have a scalable parent element to easily scale, like you are doing.  Would there be any downside to this approach?

It's a breaking change, so we'd probably want to merge it to a `v0.4.0` branch.

**Comment by jmuel** [comment]
That's basically what I was intending to do. The important thing here is that we have the overall height and width which goes on the svg element itself and should be a string, and we have the internal height that is used for measurements and should be a number. I was thinking we could actually create a separate prop for the first concept and keep the height and width the same, and default the svg's height and width to the internal height and width if there's no scaled values. This would allow us to make it a non-breaking change, but it might have additional complications I'm not thinking about.

**Comment by esbullington** [comment]
Actually, it doesn't even have to be a breaking change even without a separate height.  We could either not validate those propTypes or (better yet) use the React `oneOf` validator:

```javascript
    // An object that could be one of many types
    optionalUnion: React.PropTypes.oneOfType([
      React.PropTypes.string,
      React.PropTypes.number,
      React.PropTypes.instanceOf(Message)
    ]),
```

I've been working in statically-typed languages recently, so I momentarily forgot the fact that I'm working here in JS (`propTypes` trick me into thinking I'm working in static types, even if the validation is in fact runtime).

That said, it's not a bad idea to set the default height and width to `100%`, which should accomplish pretty much what you're suggesting.

**Comment by yang-wei** [comment]
Yes this is not a breaking change. PR are welcome @jmuel

**Comment by samdalton** [comment]
I ran in to this issue as well, but because of AreaChart, you can't accept both a string and a number as it does math with the values. See my comment here: https://github.com/esbullington/react-d3/issues/179#issuecomment-95329569
This would work for LineChart but if we wanted the interface to be consistent across all charts it needs a different approach.

**Comment by esbullington** [comment]
Thanks for reminding me @samdalton   I've started a new job doing mobile development in Java and Objective C and spent the past few weeks immersed in those languages, so I've not been able to keep this code base in my head.  I shouldn't have answered so glibly without referring back to the code.

So the way I had planned on doing this originally was putting a listener on window `onresize` event and resize the chart width and height accordingly.  I forgot while answering that I have to calculate an inner width and height to account for the chart margins.   And we can't simply query the SVG object for the rendered width and height using `getBBox` for these calculations, because this is all done in React before the chart is rendered in the browser.

There's also another [really elegant way](http://blog.scottlogic.com/2015/02/02/svg-layout-flexbox.html) to calculate margins using Facebook's CSS css-layout library that enables cross-platform flexbox layout, but unfortunately it would require recalculation once SVG has rendered, ruling it out for a "pure" React framework.

But Sam's idea is another possible approach. The only two problems I see with this approach are:

1.  Proliferation of props: adding 4 more props to an already large number of props.  Of course, the easy way to simplify to that is to stick those 4 props into a single viewbox object prop, similar to our margins prop.
2.  Viewbox is not totally cross-platform: it's not properly supported by IE until IE12 (supposedly IE12 supports it properly), if I'm not mistaken.  Yes, I'd like to just forget about IE < 12, but I'm guessing a lot of people using this library have to support IE.

But Sam's approach has a big advantage in that it's guaranteed to scale like the parent element.  If I recall from past d3 projects, that's sometimes been a problem with `window.onresize`.

Sam, are you using your viewbox approach now?  Have you tried tested it on IE?

**Comment by samdalton** [comment]
@esbullington funny you should mention the `onresize` approach - that is what we ended up doing as an interim solution. There was some catch to calculate the correct inner width inside the parent container which @parshap can elaborate on. I did try out the method I suggested in Chrome, however, and it worked well.

I like idea of passing in an viewbox object with the 4 properties, but was not aware of the IE compatibility < 12 issue which is definitely problematic. Maybe looking in to the failure mode and then providing a fallback for IE9+ could be an option.

**Comment by yang-wei** [comment]
Close due to inactive. Please open a new issue to make further discussion.
