### ISSUE TITLE
How to add second Y-axis in LineChart?

### ISSUE THREAD

**Issue by n1mda** [esbullington/react-d3#209]
I need multiple axes in a LineChart, how is this done in react-d3?

**Comment by yang-wei** [comment]
@n1mda  It's not possible with the current exposed api provided but you can do it easily since most of the elements in React-d3 are modular.

Just copy `LineChart.jsx` inside `src/linechart` to something like `multipleAxesLineChart.jsx`.
Inside the `render` method, say you want to add another yAxis on the right side of the graph.
```js
// multipleAxesLineChart.jsx
   return (
      <Chart ... >
          <XAxis ... />    <--- default xAxis
          <YAxis ... />    <--- default yAxis
          <YAxis                            <---- add this
             yOrient="right"
             yScale={yourScale}
              ....
          .../>
        </g>
      </Chart>
```

Hope that this solve your problem. If you have further question, try to show us what kind of data you have and what kind of axis you want to add. Cheers.

**Comment by MatthewHerbst** [comment]
This is actually a feature I've been planning to add since it is a fairly common use-case. The hard question about it is the fact that either the data array will need to be modified, or, two data arrays, one for each axis, will need to be passed. I like the latter option better. Something like:

```javascript
<LineChart
   ...
   xData={dataForXAxis}
   yDaya={dataForYAxis}
  ...
>
```

**Comment by yang-wei** [comment]
@MatthewHerbst This feature was talked somewhere else in issues. However it would be really cool to have this. Just the difficult part is how to expose it.

From what I understand, you mean that if we need another yAxis, we simply do something like:
```
<LineChart
   ...
   xData={dataForXAxis}
   yData={dataForYAxis}
   yData={dataForYAxis}  <--- another y axis
   ...
/>
```
is it?

**Comment by esbullington** [comment]
Hey, I'd love to make it easy for users to do things like this.  However, I'd prefer to work toward making it easier for users to compose their own charts using our chart primitives, rather than adding yet another prop to the top-level charts (`LineChart`, `ScatterChart`, etc).  @yang-wei demonstrated one possible way to do this above.  

If contributors can come up with better ways to compose the underlying chart components, or improve the underlying components, or would like to help document this approach with examples, that would be great.  Right now, the best examples for this can be found in the code for the top-level charts themselves.
