### ISSUE TITLE
Changing length of data array breaks line-charts due to index based keys

### ISSUE THREAD

**Issue by davidgtonge** [esbullington/react-d3#212]
First, thanks for this library - I love the approach.

I've run into an issue where I get loads of these errors:
`Invariant Violation: replaceState(...): Can only update a mounted or mounting component`

This was caused by re-rendering with a new data array with additional data points at the start. The issue seems to be the fact that the child circle elements have a key based on the index in the array.

I added a `keyAccessor` prop that is a function accepting `(d, i)` and by default returns the `i`, but could be supplied as a custom function that returns a unique key - for the times when the index doesn't always refer to the same element. (D3 allows exactly the same mechanism). This fixed the problem, however I lost the animation. I started tracing the Voronoi code path, but thought I'd check in here first as it seems like @yang-wei is working on refactoring that code.

I'd like to suggest that there are lot of values / accessors that should be changed over to the D3 standard of `function (d, i) {}`. D3 uses the `functor` utility method to turn static values into functions.

Would you be OK with me submitting a pull request for this, a quick example off the top of my head is the `fill` prop for the bar chart. At the moment this can only be a static colour - but allowing fill to be supplied as a function would allow each bar to have a different fill.

Thanks again for the library.

**Comment by MatthewHerbst** [comment]
Hey @davidgtonge . If you look at #203 / #210 , you will see I have added in a `props.colorAccessor` feature to complement the `props.colors` function passed to most graph types. I didn't add it to `BarChart` yet because it requires some additional changes to the `BarChart` code which doesn't implement `props.colors` currently, but I'm working on it. Should be ready by next week.

As per the `function(d ,i)..` formatting, @esbullington has said he prefers `idx` over `i`.

I think the `keyAccessor` that you propose is a good idea because it would potentially make the keys more efficient. Make the PR and we can see what it looks like. At the same time, I am using the charts similarly to what you have done, where when I update I might have more or less data, and while I did initially encounter a similar error to what you list above, I was able to resolve it with changes to my code. Make sure your render methods are pure.

**Comment by MatthewHerbst** [comment]
Also, it is worth noting that React uses indexes by default for keys when you don't provide one, so I'm almost certain that our using the index as keys is not the cause of your problem @davidgtonge

**Comment by MatthewHerbst** [comment]
@davidgtonge I dug around in my code a bit and turns out I actually do have this same problem! so sorry for saying I didn't - I had only been testing with with updating with less datapoints, not with more. I do find it strange that React uses indexes by default and yet we are having problems using indexes, but I think the idea you have proposed with a keyAccessor would be a good fix maybe.

What I don't understand is why indexes aren't enough? They will always be unique.

**Comment by MatthewHerbst** [comment]
So, I played around with this by changing the `key` for the `Circle`s generated by `linechart/DataSeries` to `Math.random()`. I expected that to solve the problem by proving that the key was indeed the culprit. However, I get the same error. I am back to thinking it is our code that is the problem, or something other than the keys. @davidgtonge Can you show us the code you used to fix your error?

**Comment by davidgtonge** [comment]
Hi @MatthewHerbst I'll make a pull request now

**Comment by MatthewHerbst** [comment]
I have done some testing for this. @yang-wei all the voronoi animation/immstruct stuff is causing this. I commented out the code in `linechart/Line:componentDidMount()` and `linechart/Circle:componentDidMount()` and the errors that @davidgtonge and I see go away. I looked over the voronio code and the `immstruct` stuff. I have several comments:

1. I believe that the way we are using immstruct is actually a React anti-pattern. A component should not know about anything except itself, its props/state, and its children. In the current usage, a component has access to change the state of components that are not its children - it should not have that access.
2. There is a bug in the way we use immstruct. We set `props.structure.cursor('voronoiSeries').set(props.seriesName, 'inactive');` yet we don't check if there is a series name. Considering that the default is "", this will cause every dataseries to override the data of the previously created dataseries.
3. As has been talked about in #214 I really thing we shouldn't be doing any animation - that should be up to the user to implement if they want any at all. Hoping @esbullington will share his thoughts on this soon.
4. immstruct is build on top of Immutable.js. We would do better to just implement Immutable.js and then we could take advantage of the PureRenderMixin (we could use it with immstruct too, though it would be much more work).
5. Going back to point 1, it seems like you basically wanted to implement Flux/Reflux just using immstruct. I believe that actually using something such as Reflux would be more appropriate here, since then you don't run into the possibility of components directly changing eachother's state. 

@davidgtonge The fix for this bug for now is to just comment out the code in the two functions I mention above. It kills the animation (which I don't think was all that riveting to begin with), but it works.

**Comment by MatthewHerbst** [comment]
Also, an additional comment: without a deep understanding of immstruct, it is basically "black magic" how the component knows that a line is being hovered and should be animated. I still can't figure it out - was searching for an `onMouseOver` or something. I would love an explanation of how this happens - I assume it is something to do with the `observe()` function.

**Comment by davidgtonge** [comment]
Hi - sorry I got pulled onto other things and wasn't able to get the pull request done.
I agree with keeping the library minimal - to be honest the immstruct and voronoi code put me off using this library. 

That said - the basic implementation is excellent.

**Comment by esbullington** [comment]
Hey no problem, thanks for closing the issue.  

Regarding the immstruct dependency, Yang-wei actually [removed the immstruct dependency](https://github.com/esbullington/react-d3/commit/3054e05f9f0b3195f01b5be2571adea9f4a636d4) a couple of weeks ago. 

Was it the Voronoi graphics or the Voronoi implementation that put you off?
