### ISSUE TITLE
Suppress treemap labels when rectangle is too small

### ISSUE THREAD

**Issue by ejaxon** [esbullington/react-d3#217]
Ok, now I've hit the next tricky bit: dealing with labels that don't fit into the rectangle in the treemap (this will happen in every single layout I'll have). In general, the sequence in a treemap is:

* Show the full label if there's room
* Otherwise show the first part of the label followed by `...` if there's room for a few letters and the ellipsis
* Otherwise suppress the label (and possibly turn on a tooltip)

The problem is that in order to know the size of the SVG text element you have to create it, which doesn't work in the virtual DOM in React. Also, this problem _has_ to be solved in the treemap component ... I can't do it from outside.

Even inside, the only time you can actually get the element is after componentDidMount - not sure what to do with it then.

You can use some rule of thumb to estimate the width of the text element ... that's not good, but not too hacky. The standard thing I've found out there is to create it invisibly using something like [Raphael](http://raphaeljs.com/)) and getting the bounding box, but you'd have to require a workspace-element in the DOM outside React control ... in other words, a real mess.

Any other ideas? This is a standard visualization issue - it's bound to crop up other places in the library.

**Comment by ejaxon** [comment]
I've gone with passing in an average character width parameter (actually added inside an `extraProperties` hash so I don't have to keep adding things). Not recommending the approach, but it's all I have time for at the moment.

**Comment by MatthewHerbst** [comment]
The Treemap creates the SVG and sets its size, so why would it not know the size of the text element?

**Comment by ejaxon** [comment]
You can only get the size of the text element _after_ the element is rendered in the DOM (nothing to do with React, that's a standard issue in SVG - it depends on the string and the font at least, maybe other things). Apparently the way you do this in the regular SVG world is create it invisibly and then get the bounding box. That's already ugly, but in the React world you have to reach out to the actual DOM to do it.

**Comment by yang-wei** [comment]
@ejaxon Had you come with any solution ?

**Comment by esbullington** [comment]
Eric's correct.  The only way to get the size of the text element is *after* the element is rendered.  As such, there's no way I can think of to solve this issue (we do everything in React, pre-DOM, so people can use the library on the server, and for other reasons).

In individual cases, people can resort to character counting, since they'll know how their font metrics.  But as a library, it would be very hard for us to keep a running tally of the font type and font size, and their corresponding character widths.

While investigating this problem initially, I did create a small React utility for self-wrapping SVG text: https://github.com/reactiva/react-svg-text

I'll leave this open to see if anyone else can think of an alternate solution, but I've thought about this a lot and can't come up with anything.

(side note: I've been unable to help out with the project much recently as things are very busy at my new job, which will likely be the case until the end of June)

**Comment by ejaxon** [comment]
In the near term, I don't see other options. Hopefully in the future React will provide a middle way. There are cases (not just SVG text) where one needs to build the components in order to determine a size, but it would be nice not to have to actually mount and render them in the actual DOM. Although in this case I'm just using knowledge of the font characteristics as @esbullington noted, I've also got other cases where I componentDidMount/componentDidUpdate triggers a test to make sure that sizing is correct and iterates one additional time if not.
