### ISSUE TITLE
Should hover effects change state

### ISSUE THREAD

**Issue by Kevnz** [esbullington/react-d3#234]
I was creating an interactive Line Chart and noticed that hover changes state of the circles, however if I am trying to render the chart again React throws an error for changing state during the render cycle. Would this be better as a direct DOM change and bypass state? That way the chart can rerender safely? I would be happy to submit a PR for this, but before I do that I'd like to know if there is any history or baggage or scar tissue associated with this or if I'm just way off base.

**Comment by MatthewHerbst** [comment]
What do you mean by "render the chart again?"

Can you show us some of your code?

In principal, React code should never interact directly with the DOM - that's the entire reason React exists in the first place - DOM interaction is very, very slow.

**Comment by Kevnz** [comment]
https://github.com/Kevnz/x-change-ui is the code, the site can be seen at http://x-change-ui.divshot.io/, interactive chart that lets you add more currency comparisons, so if you click get, then hover over the chart the state is changed for the hover effects over the lines and circles. This will throw errors when the chart data is updated and the render cycle happens as the chart has changed. It would seem that mouseover effects are a bad place to manipulate state in this instance. 
As for direct dom manipulation, css styles could be used in it's place, but really, I'd rather have slow than errors.

**Comment by MatthewHerbst** [comment]
Not sure I see the problem - I was able to add some lines, then do some hovering, then add some more lines and didn't see any console errors.

(Though I would recommend checking to see if input is a number :) )

**Comment by Kevnz** [comment]
The sample is just a toy app. To replicate the issue just move the mouse around the chart after adding a second currency range. It makes sense as well when you consider that change state causes a rerender for that node then possible right after the data for the chart is updated and you get
"Uncaught Error: Invariant Violation: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state."

**Comment by Kevnz** [comment]
Also, in the project contributing guidelines it says to avoid state whenever possible.
*"Please try to avoid React `state` to the extent possible. Ideally, data should be passed in to the top-level chart via `props` and then passed down to child components as needed.  This isn't because React `state` is inherently bad, but it breaks referential integrity, makes it hard to reason about errors, and prevents certain optimizations that are otherwise possible."*

**Comment by esbullington** [comment]
Right, it's a tricky issue: the chart animations have been by far the trickiest state issue to deal with, and have consistently been the only exception to our preference for avoiding React state mutations.

Unfortunately, by definition, mouseover effects involve state change.  Whether that state change takes place in the DOM (as you suggest), by the browser in CSS, or in React, it has to happen somewhere.  React states changes could be stored in a top-level component and cascaded down (which we've tried using functional cursors), but that state change still has to occur somewhere, which leaves the app vulnerable to the invariant violation error you describe. 

We're not going to mutate the DOM, that's pretty much out of the question for this particular project.  CSS is an interesting idea.  The problem is that to get similar kinds of SVG hover effects as we have now in CSS using transparent overlays, we need CSS pointer events, which isn't supported until IE 11.  Up to now, we've been trying to support IE10+ but it may be time to give up on that goal.

That said, the error shouldn't cause any problems with the app: it's just letting you know that it can't apply the hover effect at the exact time you're adding or removing a series.  But it's definitely not ideal, so if you can think of any ways to fix this without mutating the DOM, or restructuring the entire library, your input is welcome.

I hope to have some significant time in a week or two to work on the project, so I'll revisit this issue at that time.  Thanks for reporting it, appreciate it.

**Comment by BigDataSamuli** [comment]
I think the error is rather caused by Kevnz's code changing the components state directly, see https://github.com/Kevnz/x-change-ui/blob/master/app/main.js#L30-L32

You assign state.data array to a local variable and then push to it, which mutates the components state directly because the local variable still references the actual state object. You need to make a shallow copy of the state array before mutating it and then pass the new array to setState.

**Comment by Kevnz** [comment]
Actually @BigDataSamuli that has nothing to do with the error, it happens regardless. As the setState changes the data and causes a render, the mouseover changes state during the render process, hence the error.

**Comment by BigDataSamuli** [comment]
Ok sorry, the error message didn't really correlate with that anyway. I just though that calling setState was only prohibited directly inside the update or render path and that the mouseover events would have been queued somehow, but I guess not.

**Comment by yang-wei** [comment]
Close due to inactive. Please open a new issue to make further discussion.
