### ISSUE TITLE
No more /** @jsx React.DOM */

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#26]
@esbullington  Hey, I don't know if you noticed that start from React v0.12, we no longer need to add `/** @jsx React.DOM */` on top of our jsx files. You can see the detail on the [official blog](http://facebook.github.io/react/blog/2014/10/28/react-v0.12.html#jsx-changes). So we can start removing all these comments since we are using v0.12.1. 

Anyway feel free to close this issue if you think that it's great to support React older than v0.12

**Comment by esbullington** [comment]
Oh yeah, thanks for the reminder.  I had forgot about that.  Yeah, if we're only support >=0.12.0, then we can remove them.  I looked around at some of the other big React libraries, like React-Bootstrap and React-Router, and it looks like they're only supporting v0.12 and up.

However, we should probably wait until we release 0.2.0 for this, as it's a breaking change (as is my `props.color` change).

I'll leave this open until we either remove these pragmas or determine how long we're going to keep them for.

**Comment by esbullington** [comment]
Hi @yang-wei I went ahead and removed the pragmas, since:

1) We're already requiring React >=0.12 as a dependency
2) We compile all that jsx anyway before it's published to npm, so it should matter not for regular users

Thanks again for bringing it up; I'm closing the issue now.  Feel free to re-open if you have any addition concerns/questions.
