### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by coderjonny** [esbullington/react-d3#331]
Hi, 

Awesome graphs.. but for further configuration like changing colors, how would you do that?

**Comment by matsad3547** [comment]
@coderjonny, how did you end up changing the colors for your graph?  I'm trying to figure that out and haven't seen any documentation on how to do it yet.  The fill attribute doesn't seem to have any effect.

**Comment by yang-wei** [comment]
color is done via passing in `colorAccessor` props

https://github.com/esbullington/react-d3/wiki/CartesianChartPropsMixin

anyway if you are using react-d3 with new project please have a look at https://github.com/yang-wei/rd3

**Comment by matsad3547** [comment]
Thanks for your reply!  I actually moved away from react-d3 for the reason
of colors and to get a fixed y-scale (I was using the bar chart) because I
need to compare several sets of data and the relative size difference is an
important part of the visualization.  Is there a provision in react-d3 for
a fixed y-axis scale for bar charts?

**Comment by yang-wei** [comment]
what do you mean by a fixed y-scale ? 

In https://github.com/yang-wei/rd3 you get to customize your own y-axis including the scale. Can this help ? https://yang-wei.github.io/rd3/docs/new/axis.html

**Comment by matsad3547** [comment]
The y scale changes with the max y value of the data I put in so that the
highest bar is always the rendered the same height, even though they are
different values.  I need them to render to heights proportional to their
values.  Does that make sense?
