### ISSUE TITLE
Specifying appearance alongside data in series

### ISSUE THREAD

**Issue by berrytj** [esbullington/react-d3#41]
To use piechart as an example:

The API for passing data to a piechart is a list of {label: label, value: value} objects.  I'd like to be able to pass down appearance information, associated with each piece of data.  For instance, in one case I'd like to specify varying opacities for the arcs of the piechart.  There are two ways I can think of to do this:

1) Add an "appearance" field to the data (so it would be a list of {label: label, value: value, appearance: appearance}).
2) Pass down an "appearances" list that matches the data list index for index

In both cases, the "appearance" values would be objects containing arbitrary appearance fields.  Any fields we want to put in there we'll have to add to the actual element creation step, with defaults.

I think option 1 is simpler, but maybe mixes concerns?

**Comment by esbullington** [comment]
Thanks for your comment.

Yes, this type of use case is exactly what I had in mind when I spoke of a [second chart API](https://github.com/esbullington/react-d3/pull/9#issuecomment-66976230) using the `DataSeries` components that are now internal to multiple chart types.  I'll export all the chart components before 0.2.0, including the `DataSeries`.  And then you can use them exactly as they're now used internally to compose the core chart types.  I'm also taking care to expose all the important variables inside each component as props, so you'll be able to access them, change them, and (in some cases) style them as you wish.

This is the beauty of React components.

The other way you can style these charts is to use CSS, including `nth-child` for selecting elements by index.  If you see an SVG element that you'd like to style, and it doesn't have a hook, please feel free to submit an issue or PR adding a class to that element.  I realize CSS won't hit 100% of use cases, but it should cover most of them.

At this time, I'd prefer not to add any additional complexity to the core chart components, since those are the ones that end users who just need a quick chart will use.  So your option number 1) is not possible (plus, as you say, we'd fall deeper into overlapping concerns).  If you're not happy with how much you can customize the charts once all their internal components are exported, and with CSS, then perhaps we could revisit the possibility of something akin to your proposal option 2) sometime after 0.3.

If you need this feature right now and CSS doesn't work, then I suggest forking the repo and adapting the piechart component to your needs directly.

**Comment by berrytj** [comment]
Okay, that makes sense.  CSS is good enough.  Thanks.
