### ISSUE TITLE
Add `dist/public/js/main.js` in `.gitignore`

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#50]
Do you have a way to only commit this on *gh-pages* branch ? This file changes so much each time and I think this can make our commits better =)

**Comment by esbullington** [comment]
Hey @yang-wei thanks for the pull request!  I'll be out of my office this morning but I'll take a close look at the PR and your other questions when I get back this later in the morning.

But yes, I agree that we need find a better way to do documentation and example builds, probably by moving that stuff to its own repo.  Right now, the examples main.js has to be checked into git in order to merge it with the gh-pages branch (it uses git subtree).  But I agree that it's a pain to work with like that.

I'll write more later this morning...

**Comment by esbullington** [comment]
Anyway, I agree that this is not a good setup.  I'm going to setting up a separate repo for the website and documentation in the next few days, at which point we can add the build to .gitignore.

**Comment by esbullington** [comment]
Hey, @yang-wei Done.  The website builds now to the ./build directory, which is in .gitignore.  When we want to publish a new version of the site, I'll just manually copy it to react-d3-website.

**Comment by yang-wei** [comment]
Thank you for your hard work. Appreciate this
