### ISSUE TITLE
Reusable method

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#58]
Hey, as I'm writing test for voronoid, I realised that there are a few methods I need to reuse. Those methods are

 * concat all data into `allValues`
 * `_calculateScale`
 
I do think that it's good to factor out this method in `util.js` or as a (mixins)[http://facebook.github.io/react/docs/reusable-components.html#mixins]. I suggest to add another `/src/mixins/` folder so that we can add resuable code here.

However we can do this in the next publish if you think that there are too much to do. No worries :smile:

**Comment by esbullington** [comment]
`mixins` are good if the code you're factoring out needs access to the React components instance (e.g., if it needs to access `this.state` or `this.props`, or if the mixin needs to add a component lifecycle).

Otherwise, just a `utils.js` would be good.  Sounds like in this case probably just a `utils.js` would work.

**Comment by yang-wei** [comment]
@esbullington  Sounds good. Do you want to take over this or it's ok to let me factor out those reusable code.
I will put them in `src/common/utils.js` =)

**Comment by esbullington** [comment]
> Do you want to take over this or it's ok to let me factor out those reusable code.

Sure,  you're welcome to if you'd like.  But would you mind putting that in a separate PR from the Voronoi?

But if you don't get to it, I'll remember to factor that out later.

**Comment by esbullington** [comment]
Thanks, @yang-wei I merged that PR.  I moved it from `src/common` to `src` since I'm planning on keeping only React components in the `src/commons` directory.  I'm probably going to make that a separate NPM package soon, something like react-d3-components.  If the `utils.js` gets big enough, we should probably break it out into a `src/utils` directory, or maybe even a react-d3-utils package.

I removed the lodash dependency -- no more lodash.  In its place, I'm using a lot of ES5 functional features like `map` and `forEach`, along with the ES6 arrow functions.  I considered using 6to5 for ES6, but I'm sticking with the ES6 features offered by reactify:

* arrow functions
* destructuring
* ES6 template strings
* object short notation

But for now, let's not use:
* ES6 classes (no need with React classes, mixins, and regular JS prototypal inheritance)
* `const` and `let` are unfortunately not available with reactify, which is too bad

By the way, I went ahead and added you to collaborators list so you can go merge your own PRs if they're small and if they pass all tests.  That doesn't mean there there's now any pressure to regularly contribute -- just whenever you want!

But I'd ask you to please let me review if you're adding a new chart or major feature, and I'll do the same if I'm adding a major new feature or chart (if that's OK with you).  Oh, and please don't forget to run `npm lint` before you make a PR.

We passed 100 stars on Github today :)  And growing fast.

I'll let you close this issue when you've read this.

**Comment by yang-wei** [comment]
@esbullington Thank you for adding me as a contributor, much appreciated. I like the idea of `react-d3-components`. All above are noted. 

Yeah this is growing faster than what I thought. Congrats ! Let's keep this go on =)
