### ISSUE TITLE
Issues including external scripts for use as webpack external dependencies

### ISSUE THREAD

**Issue by andycmaj** [esbullington/react-d3#65]
Getting a server-side error message trying to render a react component that depends on React-d3.js.

Error:
<pre>
Error while loading &quot;~/scripts/externs/react-d3.min.js&quot;: ReferenceError: document is not defined
    at Script Document [7]:9:29125 -&gt; 3_array=function(list){return d3_arraySlice.call(list)},d3_document=document,d
    at Script Document [7]:13:26437
    at s (Script Document [7]:6:559)
    at Script Document [7]:6:610
    at ./areachart (Script Document [7]:6:9775)
    at s (Script Document [7]:6:559)
    at e (Script Document [7]:6:726)
    at Script Document [7]:6:743
    at Script Document [7]:6:272
    at Script Document [7]:6:277
Line: 9
Column:29125
</pre>

Scenario:
- Webpack bundle including a react component that requires 'd3-react' library.
```javascript
'use strict';
var React = require('react'),
    BarChart = require('react-d3').BarChart;
var Test = React.createClass({
  render: function() {
    var barData = [
      {label: 'A', value: 5},
      {label: 'B', value: 6},
      {label: 'F', value: 7}
    ];
    return (
      <div>
        pretend im useful: {this.props.data}
        <BarChart data={barData} width={500} height={200} fill={'#3182bd'} title='Bar Chart' />
      </div>
    );
  }
});
module.exports = Test;
```
- Webpack entrypoint including Test.jsx
```javascript
module.exports = {
  Test: require('expose?Test!charts/Test')
};
```
- Webpack config specifying externals including 'React' and 'react-d3'.
```javascript
externals: {
  // Don't bundle these with the server-side bundle. React.NET needs these to be globals
  react: 'React',
  'react-d3': 'react-d3'
},
```
- Server-side ReactConfiguration including 'react-d3' script.
```csharp
            React.ReactSiteConfiguration
                .Configuration
                .AddScript("~/scripts/externs/react-d3.min.js")
                .AddScript("~/scripts/c/server/Charts.js");
```

**Comment by andycmaj** [comment]
Forgot to mention, I'm using the V8 Engine. I'll try with MSIE as well.

**Comment by esbullington** [comment]
I'm not familiar with Webpack, or with React.net.  However, I can tell you by the error message that you're missing `jsdom`, which is a d3 dependency.  In theory, d3 should pull that in if you're using NPM.  However, I believe that there may be some issues with jsdom and Windows, since it may require separate compilation. 

Check out the jsdom installation instructions for Windows from the jsdom team here: http://www.steveworkman.com/node-js/2012/installing-jsdom-on-windows/

If you still have problems after you've installed jsdom (and you also may need to `npm cache clean` and reinstall react-d3 after you install jsdom).

Ideally, we'll eventually not need the part of d3 that's pulling in `jsdom`, but that's probably a few minor version releases away.

**Comment by andycmaj** [comment]
Thanks! Sorry actually i meant to post this to the React.NET project :)
but this may be helpful too.

**Comment by andycmaj** [comment]
Out of curiousity, what's the part of d3 that uses JSDOM that you want to get rid of... maybe I can help.

**Comment by esbullington** [comment]
@andycmaj Unfortunately, it's a pretty big job: we need to be able to reproduce the SVG axes that are rendered by d3 in pure React.  All the other chart components are in pure React -- d3 is only used most of the time for path and scale calculations.  I'm planning on tackling this for v0.5 (and we're just about at 0.2 now).

But there are a lots of other contributions you're welcome to do right now.  Are you familiar with d3?
