### ISSUE TITLE
Using Dates as Linechart X axis

### ISSUE THREAD

**Issue by jmuel** [esbullington/react-d3#70]
Is this currently supported? If it isn't I can see what it takes to make it work and put in a pull request. It seems like it should be fairly easy though since d3 has some built in libraries for this sort of thing.

**Comment by yang-wei** [comment]
@jmuel  From what I know this is currently supported. You can check the source code [here](https://github.com/esbullington/react-d3/blob/master/src%2Fcommon%2Faxes.jsx#L47). Or you can see the areachart example in the [demo page](http://esbullington.github.io/react-d3/)

**Comment by esbullington** [comment]
Hi, @jmuel thanks for opening an issue.  Our axes components do support using dates, but I've not yet expanded the `LineChart` component to deal with them (in fact, `AreaChart` is currently the only one that handles dates, but it doesn't handle multiple series yet).  Let me look at how to handle this, since it's going to require special casing in multiple components.  I'll try to fix this in the next day or two, since it's an important feature.

**Comment by esbullington** [comment]
@jmuel I'm thinking of the most flexible tick label interface I can offer users, and yet still avoid having the chart components full of special casing.  What do you think about having something like:
```
var areaData = [
  {x: 1177646400000, y: 582.13}, // date is indicated in UNIX time
  {x: 1178078400000, y: 603}
];
var dateFormatter = d3.time.format("%m-%Y"); // formats date objects as e.g. 12-2015
var tickFormatter = function(d) { 
  return dateFormatter(new Date(d)); // We have to turn UNIX time to date object
};
<AreaChart
  data={areaData}
  xAxisTickCount={4}
  xAxisTickFormat={tickFormatter}
/>
```
With this approach, we're always passing in numbers, specifically seconds since the UNIX epoch, and not date objects.  So how to get the labels we want on the axis ticks?  Well, by putting a function in `xAxisTickFormat`.

This particular example makes use of d3's powerful [time formatter](https://github.com/mbostock/d3/wiki/Time-Formatting).  Although you could also use any function that takes a number and turns it into a label, I expect d3's time formatter or [number formatter](https://github.com/mbostock/d3/wiki/Formatting#d3_format) would cover most use cases.

We would probably create some easy pre-made functions people could stick in there, which would allow people to pass in a simple formatting string.  So there won't even be a need to make a custom function like I did above.  But when people need flexibility in how to display dates, it's there.

And people could use it for more than dates, of course.  You could make a function to concatenate a currency symbol in front of the number, for example.

This is actually what I had intended to do to begin with, which is why the `AreaChart` example (incorrectly, I see now) uses UNIX time instead of JS Date objects. 

@yang-wei what do you think of this approach?  This would let us avoid the headache of special casing date objects and instead treat everything as a number.  And yet it gives users all the flexibility of d3 in how to format the tick labels.  Behind the scenes, all the `d3.time.scale` does is use the linear scale with Date objects, with the tick labels automatically formatted.

**Comment by esbullington** [comment]
The main downside I can think of to this approach is that it doesn't account for things like leapyears and daylight savings if you're displaying dates as a long, uniform continuous series.  But at the savings of significant complexity for our library.

**Comment by jmuel** [comment]
Yeah, this seems like the easiest way to do it while still solving most of the problems.

**Comment by jmuel** [comment]
I'm just checking in to see if the work has been done for this. If it hasn't I can take a stab at getting it working like you described.

**Comment by esbullington** [comment]
Yes, it's supported, at least in the multi-series charts, including `LineChart`.  I forgot to close the issue. 

I ended up supporting passing in dates directly, instead of just a formatter (although I'm going to support that soon, as well).  For more, see:

https://github.com/esbullington/react-d3/wiki/Dates

The only chart that doesn't support dates and where dates might make sense is the `BarChart`, which I plan to convert to support multiple series soon.  At that time, I'll add date support.  But all the other charts support it now.

**Comment by esbullington** [comment]
@jmuel I did want to mention that I haven't yet tested the dates support much, so please let me know if you find any issues -- that would be a big help.

**Comment by jmuel** [comment]
Sure, I played around with it and it's showing time in milliseconds since the Unix epoch instead of a human readable format.

**Comment by esbullington** [comment]
Thanks, did you use an `xAccessor` to turn the Unix epoch time to Date format?  If so, can you show me your exact code, please?

**Comment by jmuel** [comment]
I tried using the xAccessor.

Here's the [project](https://github.com/jmuel/PokemonVisualizer) I'm working on.

specifically, [the chart creator](https://github.com/jmuel/PokemonVisualizer/blob/master/js/Components/UsageChart.jsx) and [the data](https://github.com/jmuel/PokemonVisualizer/blob/master/js/Services/PokemonDataService.js). I'm trying to follow your second example here (https://github.com/esbullington/react-d3/wiki/Dates)

**Comment by esbullington** [comment]
Oh, you need to specify the `xAxisTickInterval`.  I just put that example up, and forgot to include that property.

So you'd add something like:

`xAxisTickInterval={{unit: 'year', interval: 2}}`

or whatever you prefer.  

Does that work?

**Comment by jmuel** [comment]
Hmm, still isn't working. I'll see if I can do something simpler to test it.

**Comment by jmuel** [comment]
I just cloned your project and tried to run npm run-script build but it works on the assumption that you have jsx installed globally. If it isn't installed globally it will fail. I tried installing it and rerunning but I'm getting an "unknown option: --harmony" error. These are acting as hidden dependencies and keep me from just downloading, hitting npm install and having a working system.

**Comment by frederickfogerty** [comment]
I had the same thing when I downloaded. You need to install react tools over the top of jsx. 

npm i -g react-tools 

But yes, the dependencies should be listed.

**Comment by jmuel** [comment]
Thanks, that got it working.

**Comment by esbullington** [comment]
OK, I  see what happened.  You're formatting your dates two times: once in your data object, and then again in the xAccessor.  The easiest solution is probably to remove the xAccessor (the default xAccessor gets the `x` property, so it should work without an accessor in your case). 

But in the future, I'd recommend not doing that in your data -- keep it as pure data, preferably as a CSV or JSON file, so you can reuse it easily in other settings and environments.

You can do any formatting in the xAccessor.

**Comment by esbullington** [comment]
@jmuel you were also pulling in version 1.8 -- you hadn't yet updated to 2.0.  Once I updated and removed the double accessor (and stuck the data directly in the component), it rendered no problem.

And jsx isn't a hidden dependency to the actual `react-d3` package.  It's compiled to pure Javascript for the npm release.  JSX is only required for the development build.

**Comment by esbullington** [comment]
Actually, you may have pulled in 2.0, I see you had a caret.  But the double formatting was preventing it from rendering.

**Comment by esbullington** [comment]
@jmuel did you get this working?  If so, I'm going to go ahead and close the issue.

**Comment by jmuel** [comment]
I'm actually running into an issue with "Uncaught TypeError: Cannot read property 'forEach' of undefined" in line 64 of utils/index.js but there's a good chance I just messed something up when changing my data around. I'll let you know when I have it all worked out.

**Comment by jmuel** [comment]
Ok, I set up your docs page and the functionality works. The problems I'm having are in my own project. Go ahead and close it, everything's good now.

**Comment by esbullington** [comment]
Thanks, please let me know if you have any more issues.
