### ISSUE TITLE
Add animation(optional) to bar, treemap and pie charts

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#86]
Will complete this once I have time. Will open a pull request for each chart type

**Comment by esbullington** [comment]
Sounds good.  I'm going to tag this as v0.3 since the v0.2 release is just about ready.

**Comment by yang-wei** [comment]
Is `immstruct` will be a long term solution to manage state in this library? I saw in other conversation, `freezer` , `cortex` are being mentioned.

**Comment by esbullington** [comment]
Well, I really like `immstruct`, but it's bulky because of the `immutable-js` dependency.  At @rrag 's request, the creator of `freezer` kindly changed their license to one he, and we, could use for our MIT-licensed projects. Unfortunately, I was having a hard time using `freezer` like I would use a typical cursor, which is to pass a single cursor prop all the way down the component tree until maybe the next-to-last component, at which point you pass down the value fetched using the cursor/store.   So I just merged all the changes as they were, since I know people were hoping to use the axes labels.

So I may not have been using `freezer` properly.  I'll try again with it this weekend, when I get a block of free time.

In any case, I'd gladly take a PR that integrates either `freezer` or `react-cursor` into our library in such a way that we mainly are passing around a single cursor prop to each child component (or a single `store` prop in the case of `freezer`), like I am currently doing with `immstruct`.  I just don't want to end up passing around multiple props for each data key in the store or cursor (the point of a cursor is to avoid this).

So no, `immstruct` is likely not the long-term solution.  I like it but it's a big dependency for a library project.

Edit: Actually, have just looked at how @rrag is using `freezer` in his project, and I think we can maybe just adapt his mixin, if that's ok with him (we use the same license, I think).  One question, rrag: you're using you're own version of `freezer`.  Is that for the replace node feature?  BTW, rrag, react-stockcharts is looking awesome!  Let me know when you're ready to promote it.  I do have a couple of design questions, but I'll catch you on gitter for that.

**Comment by rrag** [comment]
> I just don't want to end up passing around multiple props for each data key in the store or cursor (the point of a cursor is to avoid this).

I have not used `immstruct` so I cannot compare `freezer` with it, in `freezer` you create a tree structure and pass a branch down, and that branch by can be used in the `PureRenderMixin`.

> I think we can maybe just adapt his mixin

The mixin I created is very specific for stockcharts, because I am designing stockcharts as a build it yourself chart library, I need to refactor that mixin and split into a few, right now, the `event-capture-mixin.js` is a dumping ground for all event related things. But the idea of mixin for event capture is good and I recommend using it.

Thanks for the kind words, there is a lot of work to do for stockcharts, I am still not sure if the design approach I have taken is scalable for an uber stock chart, the types created by top of the line trading systems. I am having performance issues with firefox when drawing the crosshair on mousemove. So I am in deep, figuring out what is happening.

Back to topic, I will see how you have used `immstruct` later today and update here with my comments on how to move to `freezer`. 

> One question, rrag: you're using you're own version of freezer. Is that for the replace node feature?

Yes

**Comment by esbullington** [comment]
> The mixin I created is very specific for stockcharts, because I am designing stockcharts as a build it yourself chart library, I need to refactor that mixin and split into a few, right now, the event-capture-mixin.js is a dumping ground for all event related things. But the idea of mixin for event capture is good and I recommend using it.

Sure, I mean adapt the general approach, not exactly the same implementation (which obviously wouldn't work).  Your mixin showed me that what I want to do *is* possible with `freezer`.  I think I'm going to take a related, but slightly different approach to an update pattern.  I put something up in a branch in the next few days, and also add in tooltips as a demonstration of this approach.

**Comment by yang-wei** [comment]
Single series charts animation 

Todo charts:
 
 * [ ] Pie Chart
 * [ ] Tree map
 * [ ] Bar Chart
