### ISSUE TITLE
Candlestick chart

### ISSUE THREAD

**Issue by rrag** [esbullington/react-d3#89]
I am getting started on this, few questions; please share your thoughts

1.   The data format will be

        [
            { name : "open", values : [ {x : ..., y : ... }, {x : ..., y : ... }, {x : ..., y : ... }, {x : ..., y : ... } ] },
            { name : "high", values : [ {x : ..., y : ... }, {x : ..., y : ... }, {x : ..., y : ... }, {x : ..., y : ... } ] },
            { name : "low", values : [ {x : ..., y : ... }, {x : ..., y : ... }, {x : ..., y : ... }, {x : ..., y : ... } ] },
            { name : "close", values : [ {x : ..., y : ... }, {x : ..., y : ... }, {x : ..., y : ... }, {x : ..., y : ... } ] }
        ]

2. there will only one OHLC series, meaning there will not be a DataSeries array, but just one
3. on mouse hover animation will be changing the candle stroke-width & cande fill color will darken

**Comment by frederickfogerty** [comment]
I would've thought the data would have been in the format 

    [
        {name: 'Series 1', values: [ {x: ..., open: ..., close: ..., high: ..., low: ...}, ... ]},
        ...
    ]

but that's just my $0.02

**Comment by rrag** [comment]
duh...

that makes a lot of sense, so we can have another series, which can be say volume or a moving average. Thanks.

**Comment by frederickfogerty** [comment]
Better double check with @esbullington first. Also might look into his new data format ideals, see #85 and #82.

**Comment by esbullington** [comment]
Yes, I think @frederickfogerty proposed data format is good.  I mean, I rarely see multiple series in candlestick charts, but it fits out existing data format better (which is now in the v0.2.0 branch, I'll merge it to master in the next day). 

Oh, and would you mind using colors from the `d3.scale.category20c()` palette as the default colors?  Unit tests would also be great but if you don't have time I'll be happy to do them.  And can you use the axes components from the common directory?  I hope to switch those over to native React in the next few days, but it'll have the same API, so my changes shouldn't any of your work.  That way, all our Cartesian coordinate charts will use the same axes.

Looking forward to seeing the candlestick chart, @rrag  Thanks again!

**Comment by frederickfogerty** [comment]
@esbullington excited for native React axes!

**Comment by rrag** [comment]
:thumbsup:

**Comment by rrag** [comment]
I merged from v0.2.0 and made some progress, check out my fork when you get a chance. where do you see the colors from `d3.scale.category20c()` being used?

will add the tests and send a PR

**Comment by esbullington** [comment]
Hey @rrag great I'll check the fork as soon as I can.   The colors from `category20c()` are [here](https://github.com/mbostock/d3/wiki/Ordinal-Scales#category20c).  However, note that you can create a function by doing:

    var colors = d3.scale.category20c();

And then whenever you call `colors` with an index, it returns the corresponding color from that palette.  So if you're mapping over an array of data series, you could just call `color(idx)`. Otherwise, you can use the colors manually from that palette.

Looking forward to checking it out!

**Comment by esbullington** [comment]
Hey @rrag looks great!  I haven't gotten a chance to review the code very carefully yet, but the chart itself is great!

Looking forward to your PR! Before you submit it, you'll probably want to either rebase off of master or merge, whichever you prefer.  Since it's a new chart altogether, a merge may be more straightforward.

Please let me know if you have any questions/concerns.

**Comment by rrag** [comment]
I did not explain my question about `d3.scale.category20c()` well. we have 2 colors in each candlestick series, one where close > open and other when close < open, currently I am defaulting to green and red respectively. Using a color based on the index of the series gives only one color per series, while we need 2 in this case. Some candlestick charts also use hollow ( `fill : none;` ) to indicate close > open, so using a function to get the color will limit the flexibility of this. So I guess I am trying to say we should not use a color based on series index, index we should have flexibility to pass props like

     <CandleStickChart
       data={...}
       ...
       ... 
       fillUp= {d3.scale.category20c()}
       fillDown= {d3.scale.category20b()}
       ... />

so each series can have a different color pallete, or use

     <CandleStickChart
       data={...}
       ...
       ... 
       fillUp="none"
       fillDown="green"
       ... />

I will wait for you to release v0.2.0 and merge after that, before I send a PR

**Comment by esbullington** [comment]
Understood.  I think a nice effect would be to default to `none` for `fillUp`, like you're suggesting, along with a default of `d3.scale.categoryc()` for the `fillDown`.  The reason I wanted to stick with a single d3 palette per chart is not just for aesthetics (although it's nice) but also because these palettes are designed to be high contrast and so easily distinguishable among  series.  If we mix two palettes, we might end up with two non-contrasting colors.  Not a big deal, but I'd prefer to default to `none` like you suggest for `fillUp`, and then the palette of colors from category20c() for `fillDown`. 

You could then expose the `fillDown` prop to users, who could pass in a colors function like they can do on the other charts, like you show in your first example.  If you want to expose `fillUp`, as well, it's up to you.

In a given chart, as long as there are at least a few days when the market is down at close, then that should provide good contrast between different series.  What do you think?

**Comment by rrag** [comment]
Thanks, I have gone ahead and used both `fillUp` and `fillDown` properties to the `CandleStickChart`. `fillUp` defaults to `white`. `none` wont work because it will create a no fill rectangle and the wick behind it is visible.

I also had to update the `utils.flattenData` to handle the condition where `yAccesor` returns an object (like `{open:... , high:... , low:... , close:... }`)

Like before please checkout my fork when you can. I need to add tests and will send a PR after that.

**Comment by esbullington** [comment]
Hey @rrag looks great!  Could I ask you to maybe move your flatten data function to something like `flattenObjectData` and then restore the old one to `flattenData`?  The old version supports array accessors(ie, `(d)=>d[0]`), which a lot of people use in d3.  And I'm using nested array data in one of the examples, which the new version breaks.

Alternately, you could special case nested arrays in your new version, but both your version and the original are already lengthy functions.

If you can think of some other solution, please let me know.

Other than that, looks great!  Looking forward to your pull request.

**Comment by rrag** [comment]
I see. The tests are broken, I should have run them first.

I am not going to create a new method for this as I don't see a need for it, I just made a change to include a check for `y` to be `typeof` `object`. Will send a PR with the fixes and tests soon.

**Comment by esbullington** [comment]
@rrag I'm closing this issue since your candlestick chart is merged.  Please feel free to open another one if you have any other concerns about it.
